use_frameworks!

platform :ios, '9.0'

target 'JKPerformanceManager_Example' do
  pod 'JKPerformanceManager', :path => '../'

  target 'JKPerformanceManager_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  end
end
